name: test

on: [push, create, delete, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Test
        id: selfref
        uses: ./
        with:
          token: ${{ github.token }}